name: 'balena.yml Action'
description: 'Automate the balena.yml content on push'
branding:
  icon: 'code'  
  color: 'blue'
inputs:
  path:
    description: "Specify a path to find README.md and balena.yml"
    required: false
    default: ./
  sync_readme:
    description: "Mirror the GitHub README into the Balena Hub README"
    required: false
    default: true
    type: boolean 
  sync_tag:
    description: "Match the Balena Hub version number with the pushed tag"
    required: false
    default: false
    type: boolean 

runs:
  using: 'composite'
  steps:
    # Writes the README file to balena.yml 
    - if: ${{ inputs.sync_readme == 'true' }}
      run: | 
        cd ${{ inputs.path }}
        PP=$(cat README.md) yq -i '.post-provisioning = strenv(PP)' balena.yml
      shell: bash

    # Updates the version value of the balena.yml to match the tag pushed to the users commit
    - if: ${{ inputs.sync_tag == 'true' }}
      run: |
        cd ${{ inputs.path }}
        VERSION=${{ github.ref_name }} yq -i '.version = strenv(VERSION)' balena.yml
      shell: bash
